title: Tutorials
description: Tutorial and config collection.
theme: just-the-docs

url: https://scientificmass.github.io


# Color scheme
color_scheme: paper


# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"
